version: '3.4'

networks:
  dev:
    driver: bridge

services:
  web.api:
    image: ${DOCKER_REGISTRY-}webapi
    depends_on:
      - "app_db"
    container_name: car-brand-api
    ports:
     - "8088:80"
    build:
      context: .
      dockerfile: Web.API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=Car;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Car
    ports:
     - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
volumes:
  app_data:
